server:
  port: 8888

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/movies?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

  thymeleaf:
    check-template: false
    check-template-location: false



mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.shoulaxiao.demo01.entity


#showSql
logging:
  level:
    com:
      example:
        mapper : debug

#pagehelper:
#  helperDialect: mysql
#  reasonable: true
#  supportMethodsArguments: true
#    params: count=countSql
